In [8]:
from torch import Tensor
import torch
from torch_scatter import scatter

src = torch.tensor([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
index = torch.tensor([0, 1, 0], dtype=torch.int64)
out = scatter(src, index, reduce="sum", dim=0)
out

tensor([[ 8, 10, 12],
        [ 4,  5,  6]])

In [19]:
edge_index = torch.tensor([[1, 2, 3],
                           [3, 1, 2]])
x = torch.tensor([[0, 0],
                  [1, 1],
                  [2, 2]])

out = scatter(x, edge_index, reduce="sum", dim=1)
out

RuntimeError: The expanded size of the tensor (2) must match the existing size (3) at non-singleton dimension 1.  Target sizes: [3, 2].  Tensor sizes: [2, 3]

In [20]:
edge_index = torch.tensor([[0, 1, 1, 2],
                            [1, 0, 2, 1]])
x_j = x[edge_index[0]]
print(x_j)
out = scatter(x_j, edge_index[1], dim=0, dim_size=x.size(0), reduce='sum')
out

tensor([[0, 0],
        [1, 1],
        [1, 1],
        [2, 2]])


tensor([[1, 1],
        [2, 2],
        [1, 1]])

In [17]:
x[edge_index[0]]

tensor([[0, 0, 0],
        [1, 1, 1],
        [1, 1, 1],
        [2, 2, 2]])